#!/bin/bash
set -ex

if [[ -n "${DOCKER_UID}" ]] && [[ -n "${DOCKER_GID}" ]]; then
  groupmod -o -g $DOCKER_GID user
  usermod -o -u $DOCKER_UID -g $DOCKER_GID user
  if [ $# -eq 0 ]; then
    sudo --preserve-env -u user /bin/sh
  else
    sudo --preserve-env -u user "$@"
  fi
else
  if [ $# -eq 0 ]; then
    exec /bin/sh
  else
    exec "$@"
  fi
fi
