apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-image-app
  namespace: frontend
  labels:
    app: broken-image-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-image-app
  template:
    metadata:
      labels:
        app: broken-image-app
        tier: frontend
    spec:
      containers:
      - name: broken-app
        image: nginx:1.27.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-loop-app
  namespace: frontend
  labels:
    app: crash-loop-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-loop-app
  template:
    metadata:
      labels:
        app: crash-loop-app
        tier: frontend
    spec:
      containers:
      - name: crash-app
        image: busybox:1.35
        command: ["/bin/sh"]
        args: ["-c", "echo 'Starting application...' && sleep infinity"]
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"
